name: Extract M3U8 Streams and Upload

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC (optional, remove if not needed)

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        env:
          ABC: ${{ secrets.ABC }}  # GitHub secret access token
        run: |
          python direct.py
